### ISSUE TITLE
Multiple Cursors

### ISSUE THREAD

**Issue by cbrewster** [google/xi-editor#188] opened 2017-04-12 18:57 UTC
Hi there!
I was wondering if there are any plans to support multiple cursors? I find it apart of my workflow with the text editors I use. 

If this is something you think would be useful for xi, I would be willing to help with the implementation.

**Comment by raphlinus** [comment] 2017-04-12 19:45
Hi! Multiple cursors are high on my list of things I'd like to see in xi. It also makes sense to work on them early, as selections are fundamental to many editing operations, so the more other stuff gets built, the harder it would be to retrofit them later.

Here are some thoughts about what the implementation would take. First, the existing selection state (`sel_start` and `sel_end` in `View` + `Edit::col`) obviously needs to be changed into a data structure representing multiple selections. Conceptually, this is just a `Vec<Selection>` where a selection contains start, end, col, and upstream/downstream (the latter specifies whether the cursor should be drawn at the end of the previous line or the beginning of the next when there's a line break not caused by a newline or space). I'm split on whether this should be a plain Vec, or a more sophisticated rope-based implementation. One use case to consider is a large document, select all, split selection into lines. But I'm ok with doing it simply first and optimizing it maybe later. (nb, in [Sublime API](https://www.sublimetext.com/docs/3/api_reference.html#sublime.Selection) terminology, the collection is called a "Selection" and each element is a "Range", maybe we should adopt that).

In any case, the "set of selections" struct needs methods for adding a selection (coalescing as needed), binary search, iteration, etc. It's a fairly simple stand-alone data structure.

Then, a large class of editing commands become an iteration over all selections. I'd like to see some reduction in code repetition in the movement methods (see #159) specifically, because at heart a movement is a function from a selection to a cursor position, so a generic move_selection method just iterates over that function, collecting the results.

A warning, some interactions are probably going to be very hard. In particular, input methods with composing regions interact in complex ways with multiple cursors. The way Sublime and Atom (at least) handle it is to display one copy of the composing region for each cursor. Duplicating that behavior will almost certainly require making the front-end <-> core protocol deal with composing regions explicitly. This is not simple, but it is something that makes sense for me to work on (in my day job, I'm also currently designing an IME protocol for Fuchsia, so this is relevant). But because of the difficulty, it might make sense to partially break this scenario temporarily (maybe downgrading multiple selections to one when a non-empty composing region is set, and then letting the front-end deal with it).

I hope these notes are interesting (they're useful to myself, for thinking about what I want to do, if nothing else).

**Comment by cmyr** [comment] 2017-04-12 21:04
@raphlinus, can you clarify the term "composing regions"?

**Comment by raphlinus** [comment] 2017-04-12 21:14
@cmyr, sure. The [w3c draft spec for an IME web api](https://www.w3.org/TR/ime-api/) is a pretty good introduction to input methods and why they're so important for Asian languages in particular. The "composing region" terminology is what Android's [InputConnection](https://developer.android.com/reference/android/view/inputmethod/InputConnection.html) calls it.

When you type Alt-N, then N, to get "ñ" on cocoa, the intermediate state is also a composing region containing the character "◌̃" (I think it's u+0303, not sure the exact details though).

**Comment by raphlinus** [comment] 2017-05-28 23:28
Closing this now, as cursors are multiple and the old single-cursor state is deleted. There are a number of TODO issues, briefly summarized here (and should probably be copied into new issues):

* Copy-paste of multiple lines into an equal number of cursors should paste one line per cursor. Current behavior is to paste all lines (separated by newline) into all cursors

* Transpose (^T) should rotate the contents of selection (non-caret) regions. Currently they're ignored.

* Selection region merging, when one region is forward and the other backward, always resolves the direction of the merged region to forward. I think better behavior would be to match the `other` parameter (ie the region added later).

* Update of style spans on edit is based on edit summary rather than fine grained edit, so everything from the beginning of the first region to the end of the last loses style. This is recoverable because (according to the current plugin protocol) the plugin will re-highlight all of that, but it's not ideal.

**Closed** 2017-05-29 01:19 UTC
