### ISSUE TITLE
Serialization broken

### ISSUE THREAD

**Issue by P-E-Meunier** [google/xi-editor#606] opened 2018-04-09 11:55 UTC
The design of serialization to json (`core-lib/src/rpc.rs`) seems broken, in the sense that I get panics in the deserializer when I try to send a type serialized using `serde_json`. I believe this could be improved a lot by letting serde generate the appropriate code, instead of writing custom serializers/deserializers.

Also, this would mean less code (but broken frontends).

**Comment by cmyr** [comment] 2018-04-09 13:43
@P-E-Meunier do you mean that you're trying to use the types in that file as the output types for a client, and they aren't being handled by core?

It's very possible that this won't work; that code wasn't written with the intent that it would be used by clients, and the serialization really hasn't been tested afaik.

We only use custom deserialization as a last resort. The original version of the xi protocol was written before serde was stable, and there are certain things in the protocol that serde can't automatically parse as desired.

**Comment by P-E-Meunier** [comment] 2018-04-10 06:54
This is indeed what I was trying to do: build these types, serialize them as json, send that to the server.

I've commented out the custom deserializers, added `derive(Serialize,Deserialize)` to all the types in `core-lib/src/rpc.rs`, and I've been able with this setup to do a bunch of things without any panic, like opening a view, navigating through the document, adding and deleting characters.

An exhaustive list of what is assumed to be unsupported by serde would be cool.

**Comment by cmyr** [comment] 2018-04-10 13:42
The exhaustive list of assumptions is the list of things that have custom deserializers. ;)

The issue is that the protocol as described in [the docs](http://google.github.io/xi-editor/docs/frontend-protocol.html) does certain things that serde can't handle. It makes sense that you're able to roundtrip back and forth from the RPC types, but the JSON produced when you serialize is not actually the JSON that is described in the protocol. A major example is that in the protocol mouse events are serialized as an array, which has a different length depending on whether or not it's a click or a drag event; we deserialize this into a common `MouseEvent` struct.

Similarly all `edit` commands are sent via the `edit` method, may have an inner params object containing a view_id, a method, and sometimes params; internally we store the view_id alongside the combined method/params (which are deserialized based on the method name); there isn't a way to do this with serde.

**Comment by cmyr** [comment] 2018-05-19 13:15
I'm going to close this; if there's an issue right now it's a documentation issue, in that the types in `core-lib/rpc.rs` are not intended to be used by a frontend. At some point it would be nice to have a crate that provides types for the whole protocol, but that will probably be a task for some future point where the protocol is stabilized.

**Closed by cmyr** 2018-05-19 13:15 UTC
